{% set version = "2.0.4" %}

package:
  name: gen3dictionary
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gen3dictionary/gen3dictionary-{{ version }}.tar.gz
  sha256: 6a798008f32c4a5c1833fbc03e841ebe12bb5b743812ec7c00211c0268f15c05

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - poetry
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml
    - jsonschema
    - dictionaryutils

test:
  commands:
    - pip check
  imports:
    - gdcdictionary
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/uc-cdis/datadictionary
  summary: Gen3 Generic Data dictionary
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
