{% set version = "2.0.3" %}

package:
  name: gen3dictionary
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gen3dictionary/gen3dictionary-{{ version }}.tar.gz
  sha256: 46a704e202a79be96ec08969d28885794d4825b94394103dca08e3637bd6cb82

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - poetry
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml
    - jsonschema
    - dictionaryutils

test:
  commands:
    - pip check
  imports:
    - gdcdictionary
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/uc-cdis/datadictionary
  summary: Gen3 Generic Data dictionary
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
