schema_version: 1

context:
  version: 2.0.4

package:
  name: gen3dictionary
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gen3dictionary/gen3dictionary-${{ version }}.tar.gz
  sha256: 6a798008f32c4a5c1833fbc03e841ebe12bb5b743812ec7c00211c0268f15c05

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python =${{ python_min }}
    - poetry
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - pyyaml
    - jsonschema
    - dictionaryutils

tests:
  - python:
      imports:
        - gdcdictionary
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  summary: Gen3 Generic Data dictionary
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/uc-cdis/datadictionary

extra:
  recipe-maintainers:
    - danielnachun
